// 09-day-nine-tic-tac-toe-vuejs/src/components/Header.vue
<template>
  <div class="flex justify-center q-mt-xl">
    <h4 class="text-h4 text-uppercase"><span>Day 9 :</span> Tic Tac Toe<span>.</span></h4>
  </div>
</template>

<script setup lang="ts"></script>

<style scoped lang="scss">
h4 {
  color: rgb(227, 216, 216);
  letter-spacing: 2px;
  span {
    color: #cd3545;
  }
}
</style>

// 23-translator-react/src/components/Header.jsx
import styled from "@emotion/styled";

const StyledHeader = styled.header`
  display: flex;
  justify-content: center;
  font-size: 25px;
  font-weight: bold;
  color: rgb(238, 221, 221);
  letter-spacing: 2px;
  font-family: sans-serif;
  text-transform: uppercase;
  margin: 60px 0;
  span {
    color: #dc3545;
  }
`;

export default function Header() {
  return (
    <StyledHeader>
      <span>DAY 23 :</span>&nbsp;Translator<span>.</span>
    </StyledHeader>
  );
}
