// 09-tic-tac-toe-vuejs/src/components/Footer.vue
<template>
  <footer>
    <p>© 2023 - <span>Fatima.</span> Tous droits réservés.</p>
  </footer>
</template>

<script setup lang="ts"></script>

<style scoped lang="scss">
footer {
  display: flex;
  justify-content: flex-end;
  align-content: center;
  position: fixed;
  bottom: 0;
  width: 100%;
  padding: 5px;
  background-color: rgb(31, 29, 29);
  p {
    font-size: 16px;
    color: rgb(227, 216, 216);
    margin-bottom: 0;
    span {
      color: #cd3545;
    }
  }
}
</style>

// 11-day-eleven-todolist-react/src/components/Footer.tsx
import styled from "@emotion/styled";

const StyledFooter = styled.header`
  position: fixed;
  bottom: 0;
  left: 0;
  width: 100%;
  padding: 1rem;
  p {
    text-align: center;
    font-size: 18px;
    color: rgb(238, 221, 221);
    margin: 0;
    letter-spacing: 1px;
  }
  span {
    color: #dc3545;
  }
`;

export default function Footer() {
  return (
    <StyledFooter>
      <footer>
        <p>
          © 2023 - <span>Fatima.</span> Tous droits réservés.
        </p>
      </footer>
    </StyledFooter>
  );
}
