// 11-day-eleven-todolist-react/src/components/Footer.tsx
import styled from "@emotion/styled";

const StyledFooter = styled.header`
  position: fixed;
  bottom: 0;
  left: 0;
  width: 100%;
  padding: 1rem;
  p {
    text-align: center;
    font-size: 18px;
    color: rgb(238, 221, 221);
    margin: 0;
    letter-spacing: 1px;
  }
  span {
    color: #dc3545;
  }
`;

export default function Footer() {
  return (
    <StyledFooter>
      <footer>
        <p>
          © 2023 - <span>Fatima.</span> Tous droits réservés.
        </p>
      </footer>
    </StyledFooter>
  );
}

// 18-the-simpsons-vue/src/components/Footer.vue
<template>
  <footer>
    <p><span>Day 18</span> | © 2023 - <span>Fatima.</span> Tous droits réservés.</p>
  </footer>
</template>

<script setup lang="ts"></script>

<style scoped>
footer {
  @apply flex justify-center fixed bottom-0 w-full p-1;
}
p {
  @apply text-lg text-gray-800 mb-0 font-cursive;
}
span {
  @apply text-red-700;
}
</style>
