// 24-currency-converter-react-native/App/components/Footer.jsx
import styled from "@emotion/native";
import { Text } from "react-native";

const StyledFooter = styled.Text`
  margin-bottom: 25px;
  width: 100%;
  padding: 1rem;
  text-align: center;
  font-size: 18px;
  color: rgb(238, 221, 221);
  letter-spacing: 1px;
`;

export default function Footer() {
  return (
    <StyledFooter>
      © 2023 - <Text style={{ color: "#dc3545" }}>Fatima.</Text> All rights
      reserved.
    </StyledFooter>
  );
}

// 03-dayThree-Shopping-list-vuejs/src/components/Footer.vue
<template>
    <footer>
        <p>© 2023 - <span>Fatima.</span> Tous droits réservés.</p>
    </footer>
</template>

<script lang="ts">

export default {

};
</script>

<style scoped lang="scss">
footer {
    position: fixed;
    bottom: 0;
    width: 100%;
    padding: 1rem;
    background-color: #232121;
    border-top: 1px solid #575353;
    ;

    p {
        text-align: center;
        font-size: 18px;
        color: rgb(238, 221, 221);

        span {
            color: #dc3545;
        }
    }
}
</style>
