// dayfive-music-player-vuejs/src/components/Header.vue
<template>
  <div class="flex justify-center mt-8">
    <h1
      class="text-xl font-semibold uppercase tracking-widest text-gray-200 font-serif xl:text-2xl"
    >
      <span class="text-rose-500">Day 5 :</span> Music Player<span class="text-rose-500">.</span>
    </h1>
  </div>
</template>

<script lang="ts">
export default {
  data() {}
}
</script>

// 22-drawing-app-react-socket/frontend/src/components/Header.tsx
export default function Header() {
  return (
    <div className="flex justify-center mt-4">
      <h1 className="text-3xl font-semibold uppercase tracking-widest text-gray-200 font-cursive">
        <span className="text-rose-500">Day 22:</span> Collaborative Drawing App
        <span className="text-rose-500">.</span>
      </h1>
    </div>
  );
}
